### ISSUE TITLE
Access denied for user 'root'@'192.168.xxx.xxx' (using password: YES) in docker container

### ISSUE THREAD

**Issue by ShahanMirza** [paigen11/mySqlRegistration#2]
Hi i have created mysql docker container using docker-compose file, container is up and running fine now. Docker-compose.yaml is

 ```
   version: '3'
   services:
     db:
    image: "mysql:8.0.21"
    container_name: test-mysql
    #- mysql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: Test123
        MYSQL_DB=imonitor
    volumes:
         -  vol-data:/var/lib/mysql
    networks:
         -  my-app
  backend-app:
    build: ./back-end
    container_name: back-end-container
    environment:
      - DB_SERVER= test-mysql
      - MYSQL_DB=testdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
     - 3000:3000
    networks:
      -  my-app
    links:
      -   my-app
  ui:
    build: ./front-end
    container_name: front-end-container
    ports:
      - 8090:80
    links:
      - backend-app
    networks:
      - my-app
networks:
 my-app:
  driver: bridge
volumes:
  vol-data:
```
Using interactive terminal command i have tried to get into mysql database

docker exec -it 90585b0a534a bash
root@90585b0a534a:/# mysql -u root -pTest123 mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

Also unable to connect using dB visualizer. is there any fault in yaml file or on configuration file
